from turtle import *
def iron_man(red):
    begin_fill()
    color('black')
    pensize(5)
    circle(100)
    color(red)
    end_fill()
    penup()
    goto(-83, 38)
    left(90)
    color('black')
    pensize(2.5)
    pendown()
    begin_fill()
    forward(100)
    right(65)
    forward(60)
    right(80)
    forward(22)

    left(55)
    forward(32)

    left(55)
    forward(22)
    right(80)
    forward(60)
    right(65)
    forward(103)
    color('gold')
    goto(40,15)
    
    goto(-40,15)
    goto(-82, 38)
    goto(-40,15)
    end_fill()
    begin_fill()
    pensize(2.5)
    color('black')
    left(150)
    forward(30)

    right(60)
    forward(55)

    right(60)
    forward(33)
    color('gold')
    end_fill()
    exitonclick()

def ojos():
    penup()
    goto(-66,100)
    pendown()        
    left(60)
    def ojo():
        begin_fill()
        color('black')
        forward(50)
        right(90)
        forward(19)
        right(90)
        forward(50)
        right(90)
        forward(19)
        color('white')
        end_fill()
 
    ojo()
    penup()
    right(90)
    goto(14,100)
    pendown()
    ojo()
prefer= input('what do you prefer:red or dark red?')
if prefer== 'darkred':
    red= 'darkred'
else:
    red= 'red'
iron_man(red)
ojos()
penup()
right(90)
goto(-31,30)
pendown()
color('black')
forward(69)
hideturtle()
exitonclick()
